### ISSUE TITLE
url yi otomatik çekmek

### ISSUE THREAD

**Issue by muaz742** [gelis-tr-io/PHP-Egitim-Serisi#3]
https://github.com/gelis-tr-io/php-egitim-serisi/blob/227bde1f954be3667b36d2d1a1c9cb1cfdc36eb7/bilgim-var-proje-olustururken-kafam-karisiyor/dosya-yapisi/conf/conf_main.php#L14

buradaki url yi elle girmek yerine $_SERVER['HTTP_HOST'] ile çekilse nasıl olur?

**Comment by tarikguney** [comment]
@hurata Whatcha thinking?

**Comment by hurata** [comment]
@muaz742 Geç cevap verdiğim için üzgünüm yoğunluktan bi kurtulayım seri makaleler gelecek. Sorunun cevabına  gelince  $_SERVER['HTTP_HOST'] sana çıktı  olarak "localhost" yazdırır.  Burada $url değişkeni base href olarak atanmak için kullanılıyor yani localhostta kulanıyorsan yeterli olmayacaktır.
Edit : Bir domain üzerinde çalıştığında  kullanabilirsin.  Ama başına http:// - https:// eklerini eklemeyi unutma.
Ek olarak sorularına her zaman cevap vermeye hazırım ama test etmekten çekinme.

**Comment by muaz742** [comment]
```(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]"```
sanıyorum bu kod baştaki http eklerini ekleme görevini görüyor. kendimde test ettim bende çalıştı fakat yine de fikir almadan karar vermek istemiyorum.

**Comment by hurata** [comment]
@muaz742  kod başarılı direkt  kullanabilirsin. Hatta dosya sisteminde config'e ekleyeyerek katkı sağlayabilirsin. Katkın için teşekkürler. 
İkinci bir konuda eğer test edip başarılı bir sonuç aldıysan bunu dosyalara direkt katkı yaparak gösterebilirsin burdaki amacımız zaten bir şeyleri geliştirmek  korkmadan cesurca oyna kodlarla.

**Comment by muaz742** [comment]
hemen ekliyorum
